"""Export model.json + config.json into a C header the ESP32 firmware bakes in.

  python tools/export_model.py [model.json] [config.json] [out.h]

Default output: ../firmware/libraries/hems_nilm_cpp/src/nilm_model.h

The ESP32 must not parse JSON at runtime, so everything the on-device engine
needs is compiled in: the standardised k-NN library (X, y), the scaling
(mu/sigma), k and tau, the detector/attribution thresholds, and the per-phase
candidate bitmasks built from each appliance's "phase" in config.json.

Re-run this after every train.py so firmware and Python stay in lockstep.
"""
import json
import sys
from pathlib import Path


def main(model_path="model.json", config_path="config.json",
         out_path="../firmware/libraries/hems_nilm_cpp/src/nilm_model.h"):
    model = json.load(open(model_path))
    cfg = json.load(open(config_path))

    labels = sorted(set(model["y"]))
    if len(labels) > 32:
        raise SystemExit("more than 32 classes: widen the phase bitmask type")
    label_id = {lab: i for i, lab in enumerate(labels)}

    phases = cfg["phases"]
    if len(phases) != 3:
        raise SystemExit("the ESP32 build assumes exactly 3 phases")

    # per-phase candidate bitmask over class ids (the electrician's phase map)
    masks = []
    for ph in phases:
        m = 0
        for lab, spec in cfg["appliances"].items():
            if spec["phase"] == ph and lab in label_id:
                m |= 1 << label_id[lab]
        masks.append(m)

    ed = cfg["event_detector"]
    at = cfg["attribution"]
    bg = cfg.get("background_w", {})

    X = model["X"]
    y = [label_id[lab] for lab in model["y"]]

    lines = []
    a = lines.append
    a("// AUTO-GENERATED by nilm/tools/export_model.py — do not edit by hand.")
    a("// Source: %s + %s  (%d training points, %d classes)"
      % (model_path, config_path, len(X), len(labels)))
    a("#pragma once")
    a("#include <stdint.h>")
    a("")
    a("#define NILM_NUM_CLASSES %d" % len(labels))
    a("#define NILM_NUM_TRAIN %d" % len(X))
    a("#define NILM_KNN_K %d" % int(model["k"]))
    a("#define NILM_SETTLE_WINDOW %d" % int(ed["settle_window"]))
    a("")
    a("static const char* const NILM_CLASS_NAMES[NILM_NUM_CLASSES] = {")
    a("  " + ", ".join('"%s"' % lab for lab in labels))
    a("};")
    a("")
    a("static const double NILM_TAU = %.17g;" % float(model["tau"]))
    a("static const double NILM_MU[2] = { %.17g, %.17g };" % tuple(model["mu"]))
    a("static const double NILM_SIGMA[2] = { %.17g, %.17g };" % tuple(model["sigma"]))
    a("")
    a("// standardised training features (|dP|, |dQ|), matching Python exactly")
    a("static const double NILM_TRAIN_X[NILM_NUM_TRAIN][2] = {")
    for row in X:
        a("  { %.17g, %.17g }," % (row[0], row[1]))
    a("};")
    a("static const uint8_t NILM_TRAIN_Y[NILM_NUM_TRAIN] = {")
    for i in range(0, len(y), 24):
        a("  " + ", ".join(str(v) for v in y[i:i + 24]) + ",")
    a("};")
    a("")
    a("// per-phase candidate class bitmasks, order: %s" % ", ".join(phases))
    a("static const uint32_t NILM_PHASE_MASK[3] = { 0x%08Xu, 0x%08Xu, 0x%08Xu };" % tuple(masks))
    a("")
    a("// event detector")
    a("static const double NILM_STEADY_BAND_W = %.17g;" % float(ed["steady_band_w"]))
    a("static const double NILM_DP_MIN_W = %.17g;" % float(ed["dp_min_w"]))
    a("")
    a("// attribution")
    a("static const double NILM_SAMPLE_PERIOD_S = %.17g;" % float(cfg.get("sample_period_s", 1.0)))
    a("static const double NILM_QUIESCENT_W = %.17g;" % float(at["quiescent_baseline_w"]))
    a("static const double NILM_OVER_TOL_W = %.17g;" % float(at["over_attribution_tol_w"]))
    a("static const double NILM_BACKGROUND_W[3] = { %.17g, %.17g, %.17g };"
      % tuple(float(bg.get(ph, 0.0)) for ph in phases))
    a("")

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print("wrote %s  (%d classes, %d train points, masks: %s)"
          % (out, len(labels), len(X), ["0x%X" % m for m in masks]))


if __name__ == "__main__":
    main(*sys.argv[1:])
