/* hems_nilm_cpp — on-device port of the HEMS Python NILM engine.
 *
 * Faithful translation of nilm/nilm/{event_detector,classifier,attribution,
 * pipeline}.py so the SAME model + config produce the SAME events on the
 * ESP32 as on the desktop. Verified by extras/parity (host-compiled run over
 * day_stream.csv diffed against the Python pipeline's reference output).
 *
 * All arithmetic is double precision to match Python float64 semantics.
 * At 3 phases x 1 Hz this costs microseconds per second on an ESP32 —
 * irrelevant — and buys bit-comparable parity.
 *
 * The signature library, thresholds and per-phase candidate masks are baked
 * in at compile time from nilm_model.h, generated by:
 *     cd nilm && python tools/export_model.py
 * Re-export after every train.py run.
 */
#pragma once
#include <stdint.h>

#ifndef NILM_MAX_ACTIVE
#define NILM_MAX_ACTIVE 32   // concurrent tracked loads per phase
#endif
#ifndef NILM_EVENT_QUEUE
#define NILM_EVENT_QUEUE 8
#endif
#ifndef NILM_MAX_SETTLE
#define NILM_MAX_SETTLE 16   // >= settle_window in the exported model
#endif

struct HemsNilmEvent {
  double t;          // sample timestamp (s) the event settled at
  uint8_t phase;     // 0,1,2  (config order, e.g. A,B,C -> L1,L2,L3)
  double dP;         // signed active-power step (W)
  double dQ;         // signed reactive step (VAR)
  int8_t sign;       // +1 turn-ON, -1 turn-OFF
  double levelP;     // new settled plateau (W)
  int16_t classId;   // >=0 trained class, -1 rejected/unknown
  const char* label; // class name or "unknown"
  double dist;       // standardised distance to nearest neighbour
  float confidence;  // display heuristic: 1 - dist/tau, clamped to [0,1]
  bool on;           // sign > 0
};

/* ── per-phase steady-state event detector (event_detector.py) ─────────── */
class NilmPhaseDetector {
public:
  void reset(int settleWindow, double steadyBandW, double dpMinW);
  // returns true and fills the raw step when a settled event is found
  bool process(double t, double p, double q,
               double &dP, double &dQ, int8_t &sign, double &levelP);

private:
  int W = 4;
  double eps = 8.0, dpMin = 35.0;
  double bufP[NILM_MAX_SETTLE];
  double bufQ[NILM_MAX_SETTLE];
  int bufCount = 0, bufHead = 0;
  bool hasBase = false;
  double baseP = 0.0, baseQ = 0.0;

  bool settled() const;
  void level(double &lp, double &lq) const;
};

/* ── k-NN with standardisation, rejection, phase masks (classifier.py) ─── */
namespace NilmClassifier {
// returns classId (>=0) or -1 for unknown/rejected; dist = nearest distance
int16_t predict(double dp, double dq, uint32_t allowedMask, double &dist);
}

/* ── per-phase ON/OFF tracking + energy attribution (attribution.py) ───── */
class NilmPhaseAttributor {
public:
  void reset(int phaseIdx, double dt, double quiescentW, double overTolW, double bgNominalW);
  void onEvent(double dP, double dQ, int8_t sign, int16_t classId);
  double step(double t, double measuredP);   // returns residual (W)

  double namedWh(int16_t classId) const;
  double unknownWh() const { return unknownWhAcc; }
  double backgroundWh() const { return backgroundWhAcc; }
  int activeCount() const { return nActive; }

private:
  struct Active {
    int32_t labelId;   // >=0 named class; <=-2 anonymised unknown instance
    double power, q;
  };
  double dt = 1.0, quiescent = 45.0, overTol = 90.0, bgNominal = 0.0;
  Active active[NILM_MAX_ACTIVE];
  int nActive = 0;
  double energyWh[32] = {0};
  double unknownWhAcc = 0.0, backgroundWhAcc = 0.0;
  int32_t unknownSeq = 0;
  int negRun = 0;

  void accrue(int32_t labelId, double wh);
  void removeAt(int idx);
};

/* ── orchestration: detector → classifier → attributor ×3 (pipeline.py) ── */
class HemsNilm {
public:
  void begin();

  /* Feed one sample for all three phases (1 Hz). p/q arrays are in the
   * config phase order. Returns the number of events emitted (0..3);
   * drain them with popEvent(). */
  int processSample(double t, const double p[3], const double q[3]);
  bool popEvent(HemsNilmEvent &out);

  /* energy attribution report (Wh since begin()) */
  double namedWh(int phase, int16_t classId) const;
  double unknownWh(int phase) const;
  double backgroundWh(int phase) const;

  static int numClasses();
  static const char* className(int16_t id);   // id -1 -> "unknown"

private:
  NilmPhaseDetector detectors[3];
  NilmPhaseAttributor attributors[3];
  HemsNilmEvent queue[NILM_EVENT_QUEUE];
  int qHead = 0, qCount = 0;
  void push(const HemsNilmEvent &ev);
};
